# Generated by Django 3.2.14 on 2022-07-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='date_active',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
