# Generated by Django 3.2.14 on 2022-07-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_date_active_to_puzzle_and_count_to_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
